name: Update README Stats

on:
  schedule:
    - cron: '0 0/12 * * *' # Runs every 12 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Stats Generator Script
        run: node scripts/update-readme.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: Auto-update README stats" && git push)
